### ISSUE TITLE
get data on more packages?

### ISSUE THREAD

**Issue by maelle** [maelle/niche_packages#3]
currently sampling 1,000 packages (and in fact slightly less since some of them are rOpenSci packages).

I guess it'd be ideal to just download data for all packages letting the code run over night for instance, it wouldn't change the shape of the distribution a lot but one would get the extremes like `Rcpp`.

**Comment by maelle** [comment]
if doing that instead of using "last-month" one should use dates arguments, because the current date might change between the beginning and the end of the queries.

**Comment by sckott** [comment]
what is this line doing `data <- dplyr::filter_(data, lazyeval::interp(quote(n() == 7)))` ?

**Comment by sckott** [comment]
and why the `count <- median(data$count)` ? oh, i see, you were calculating median weekly downloads

**Comment by sckott** [comment]
Seems that we can do > 1 pkg at a time from `cran_downloads` - see  https://github.com/maelle/niche_packages/tree/sckott

also tried to fiddle with plots but not sure it's better. 

with the current plot you had, downloads is on the x axis - was trying to put download on y axis, but not sure which is better/more appropriate

**Comment by maelle** [comment]
The `data <- dplyr::filter_(data, lazyeval::interp(quote(n() == 7)))` was for having full weeks only but I'll remove that by choosing dates.

**Comment by maelle** [comment]
Nice tweaks! Not too sure about the new plot though, I just need to get used to it.

I was thinking that a better plot would use `plotly` instead of `ggplot2` in order to have (rOpenSci) package names on hovering, what do you think?

**Comment by sckott** [comment]
I'm really not picky about the plot so happy to go with whatever anyone else wants to do.

**Comment by maelle** [comment]
Well do you want to put it on a page where you can have htmlwidgets?

**Comment by sckott** [comment]
yeah, interactive sounds best

**Comment by maelle** [comment]
I'll try to have a look soon! But not today :-)

**Comment by maelle** [comment]
So now there's an interactive plot. The html is just in case you want to see it without running the code.

I don't know if you've already included htmlwidgets on a blog. I'm currently in the process of learning how to correctly add some to my Jekyll blog, thankfully I'm getting help from someone who's already done it. :grin: I know that my `htmltools::includeHTML` approach in [this post](http://www.masalmon.eu/2017/02/03/chemist/) is not best practice but it worked. :joy:
